# The Docker image that will be used to build your app
image: node:lts

# The stages of the pipeline
stages:
  - build
  - deploy

# Functions that should be executed before the build script is run
before_script:
  - npm install

# The job for building the project
build:
  stage: build
  script:
    - npm run build
    - mkdir public
    - cp -r build/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH    

# The job for deploying GitLab Pages
pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r build/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

# The job for publishing the npm package
publish-npm:
  stage: deploy
  script:
    - echo "@scope:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH  