image: node:lts

stages:
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
      - package.json
  paths:
    - node_modules/
    - .npm

before_script:
  - apt-get update && apt-get install -y curl  # Install curl
  - curl -I https://registry.npmjs.org  # Check if npm registry is accessible
  - npm config set registry https://registry.npmjs.org/  # Explicitly set registry for npm install
  - npm config set timeout 60000
  - npm install

pages:
  stage: build
  script:
    - npm run build
    - mkdir -p public
    - cp -r build/* public/
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

publish-npm:
  stage: deploy
  script:
    - echo "registry=https://registry.npmjs.org/" > .npmrc  # Explicitly set npm registry for general installs
    - echo "@scope:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc  # Set registry for your scope
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc  # Set auth token
    - npm publish
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
